[tool]
id = "com.github.unfixedjuices.convert"
label = "Convert"
versionCode = 1
versionName = "0.1.0"
permissions = ["android.permission.INTERNET"]
capabilities = []
# Emulator during development. On a Light Phone III this is "com.lightos".
serverPackage = "com.thelightphone.sdk.emulator"
